name: Build Flutter Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5'  # Replace with your desired Flutter version

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4️⃣ Accept Android licenses
      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      # 5️⃣ Build APK
      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      # Move to folder
      - name: Move built file into destination folder
        run: |
          mkdir -p releases/android
          cp build/app/outputs/flutter-apk/app-release.apk releases/android/app-release.apk
      
      # # 5️⃣ Build Web
      # - name: Build Web
      #   run: flutter build web -o build/web --release

      # # Move to folder
      # - name: Move built file into destination folder
      #   run: |
      #     mkdir -p releases/web
      #     cp -r build/web/ releases/

      # 6️⃣ Upload APK as artifact
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add releases
          git commit -m "Update release artifact [skip ci]"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
